![intro](Resources/cost.png)

In [1]:
import numpy as np
from scipy.optimize import linear_sum_assignment

In [2]:
costs = np.array([[90, 76, 75, 70],
                  [35, 85, 55, 65],
                  [125, 95, 90, 105],
                  [45, 110, 95, 115],])

row_ind, col_ind = linear_sum_assignment(costs)

In [4]:
row_ind

array([0, 1, 2, 3])

In [3]:
col_ind

array([3, 2, 1, 0])

In [7]:
costs[row_ind, col_ind]

array([70, 55, 95, 45])

In [9]:
costs[row_ind, col_ind].sum()

265

In [10]:
print(col_ind+1)
print(row_ind+1)

[4 3 2 1]
[1 2 3 4]


![intro](Resources/linear_assignment.svg)

In [15]:
costs = np.array([[90, 76, 75, 70],
                  [35, 85, 55, 65],
                  [45, 95, 90, 105],
                  [125, 110, 95, 115],])

row_ind, col_ind = linear_sum_assignment(costs)


print(costs[row_ind, col_ind])
print(costs[row_ind, col_ind].sum())
print(linear_sum_assignment(costs))
print("worker : ", row_ind+1)
print("Task : ",col_ind+1)

[ 70  55  45 110]
280
(array([0, 1, 2, 3]), array([3, 2, 0, 1]))
[1 2 3 4]
[4 3 1 2]
