![intro](Resources/cost.png)

In [3]:
import numpy as np

from ortools.graph.python import linear_sum_assignment

In [4]:
costs = np.array([[90, 76, 75, 70],
                  [35, 85, 55, 65],
                  [125, 95, 90, 105],
                  [45, 110, 95, 115],])

# Let's transform this into 3 parallel vectors (start_nodes, end_nodes,
# arc_costs)
end_nodes_unraveled, start_nodes_unraveled = np.meshgrid(
    np.arange(costs.shape[1]), np.arange(costs.shape[0])
)
start_nodes = start_nodes_unraveled.ravel()
end_nodes = end_nodes_unraveled.ravel()
arc_costs = costs.ravel()

print(start_nodes,"\n", end_nodes,"\n", arc_costs)

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3] 
 [0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3] 
 [ 90  76  75  70  35  85  55  65 125  95  90 105  45 110  95 115]


### Create the solver

The program uses the linear assignment solver, a specialized solver for the assignment problem.

The following code creates the solver.

In [5]:
assignment = linear_sum_assignment.SimpleLinearSumAssignment()

### Add the constraints
The following code adds the costs to the solver by looping over workers and tasks.

In [6]:
assignment.add_arcs_with_cost(start_nodes, end_nodes, arc_costs)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int32)

### Invoke the solver

In [7]:
status = assignment.solve()

### Display the results

In [15]:
if status == assignment.OPTIMAL:
    print(f"Total cost = {assignment.optimal_cost()}\n")
    for i in range(0, assignment.num_nodes()):
        print(
            f"Worker {i} assigned to task {assignment.right_mate(i)}."
            + f"  Cost = {assignment.assignment_cost(i)}"
        )
elif status == assignment.INFEASIBLE:
    print("No assignment is possible.")
elif status == assignment.POSSIBLE_OVERFLOW:
    print("Some input costs are too large and may cause an integer overflow.")
    
print(np.array([assignment.assignment_cost(i) for i in range(4)]))
print(np.array([assignment.assignment_cost(i) for i in range(4)]).sum())

Total cost = 265

Worker 0 assigned to task 3.  Cost = 70
Worker 1 assigned to task 2.  Cost = 55
Worker 2 assigned to task 1.  Cost = 95
Worker 3 assigned to task 0.  Cost = 45
[70 55 95 45]
265


![intro](Resources/linear_assignment.svg)

### Change cost matrics

In [ ]:
cost = np.array([[90, 76, 'NA', 'NA'],
        [35, 85, 'NA', 'NA'],
        [125, 95, 'NA','NA'],
        [45, 110, 95, 115]])



# Let's transform this into 3 parallel vectors (start_nodes, end_nodes,
# arc_costs)
end_nodes_unraveled, start_nodes_unraveled = np.meshgrid(
    np.arange(costs.shape[1]), np.arange(costs.shape[0])
)
start_nodes = start_nodes_unraveled.ravel()
end_nodes = end_nodes_unraveled.ravel()
arc_costs = costs.ravel()

print(start_nodes,"\n", end_nodes,"\n", arc_costs)

assignment = linear_sum_assignment.SimpleLinearSumAssignment()
assignment.add_arcs_with_cost(start_nodes, end_nodes, arc_costs)
status = assignment.solve()

if status == assignment.OPTIMAL:
    print(f"Total cost = {assignment.optimal_cost()}\n")
    for i in range(0, assignment.num_nodes()):
        print(
            f"Worker {i} assigned to task {assignment.right_mate(i)}."
            + f"  Cost = {assignment.assignment_cost(i)}"
        )
elif status == assignment.INFEASIBLE:
    print("No assignment is possible.")
elif status == assignment.POSSIBLE_OVERFLOW:
    print("Some input costs are too large and may cause an integer overflow.")

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3] 
 [0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3] 
 [ 90  76  75  70  35  85  55  65 125  95  90 105  45 110  95 115]
Total cost = 265

Worker 0 assigned to task 3.  Cost = 70
Worker 1 assigned to task 2.  Cost = 55
Worker 2 assigned to task 1.  Cost = 95
Worker 3 assigned to task 0.  Cost = 45


![intro](Resources/linear_assignment_solution.svg)